name: Tibco Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK and Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Print Workspace Contents
      run: ls -R $GITHUB_WORKSPACE

    - name: create folder
      run: mkdir /home/runner/work/com.tibco.bw.palette.shared

    - name: Print Workspace Contents
      run: ls -R $GITHUB_WORKSPACE
      
    - name: Install Local Dependency
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of the workspace:"
        ls -R $GITHUB_WORKSPACE
    
        mvn install:install-file \
          -Dfile=$GITHUB_WORKSPACE/.m2/repository/com/tibco/plugins/com.tibco.bw.palette.shared/6.2.1300/com.tibco.bw.palette.shared-6.2.1300.jar \
          -DgroupId=com.tibco.plugins \
          -DartifactId=com.tibco.bw.palette.shared \
          -Dversion=6.2.1300 \
          -Dpackaging=jar


          
    - name: Build and Package BW6 Application
      run: |
        cd BWCE_Hello_World/BWCE_Hello.parent
        mvn clean package -P mavenize
      env:
        MAVEN_OPTS: '-Dmaven.repo.local=./.m2/repository'

    - name: Package and Publish EAR Artifact
      run: |
        cd BWCE_Hello_World/BWCE_Hello.parent/target
        echo "BW6 Application EAR file successfully built and packaged."
      env:
        MAVEN_OPTS: '-Dmaven.repo.local=./.m2/repository'



